name: GitHub Notification Cleanup

on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  archive:
    uses: ./.github/workflows/archive.yml
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

  unsubscribe:
    needs: archive
    uses: ./.github/workflows/unsubscribe.yml
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
