name: GitHub Notification Cleanup

on:
  schedule: # Every hour from 8 AM to 6 PM UTC, Monday through Friday
    - cron: "0 8-18 * * 1-5"
  workflow_dispatch:

jobs:
  archive:
    uses: ./.github/workflows/archive.yml
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

  unsubscribe:
    needs: archive
    uses: ./.github/workflows/unsubscribe.yml
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
